# some things to consider
# - only values smaller than 128 for decimal values
# - projectile limit is 16 and the game isn't even optimized for bullet hell
# - set speeds and forces to unit per second
# - MAKE SURE BOTH PLAYERS HAVE THE EXACT SAME CONFIG OR THE GAME WILL DESYNC WHEN YOU BREATHE ON IT

[GameRules]
playerHealth = 5
roundsToWin  = 2
roundCountdown = 3
roundTime = 100
roundEndTime = 3

[PlayerResources]
ammoMax        = 100    #frames for ammo to fully fill
shotCost       = 50
altShotCost    = 100
staminaMax     = 150    #frames for stamina to fully fill
dashCost       = 50

[PlayerActions]
dashPhase      = 8      #frames for normal movement to completely phase into dash movement
dashPerfect    = 10     #frames for perfect evade window
dashDuration   = 20     #dash length in frames
chargeDuration = 45     #charge length in frames

[PlayerSpeed]
playerWalkSpeed = "4.0"
playerWalkAccel = "4.5"
playerWalkFric  = "2.8"
playerDashSpeed = "24.0"

[ProjSpeed]
projSpeed = "10.0"
projCounterMultiply = "1.2"

[Radius]
playerRadius = "0.5"
grazeRadius  = "0.7"
projRadius   = "0.3"
comboRadius  = "6.0"
arenaRadius  = "12.0"
spawnRadius  = "10.0"   #distance of each player from the center

[HitStrength]
weakForce     = "1.0"
weakHitstop   = 5
midForce      = "2.5"
midHitstop   = 10
strongForce   = "4.0"
strongHitstop = 20
