# ALL CASE SENSITIVE
# home (or anything else) = home screen (plays a blurred replay in the background)
# replay                  = plays a replay
# dummy                   = match against an inert P2 to finetune your controls
# connect                 = connect to <address>:<port>
launchMode = "dummy"

[Network]
address = "127.0.0.1" #naturally, change this to IP of listener
port = 8001

[Replay]
replayFile = "demo.rbst"